version: 0.2

env:
  secrets-manager:
    CLOUDSMITH_USR: PavedRoadCodeBuildSecret:cloudsmith-write-usr
    CLOUDSMITH_API_KEY: PavedRoadCodeBuildSecret:cloudsmith-write-api-key

batch:
  fast-fail: true
  build-graph:
    - identifier: frontend
      buildspec: ./aws-code-resources/buildspec.yaml
      env:
        variables:
          BUILD_ID: frontend
          APPDIR: ./frontend
          TAGPREFIX: forntend/
          IMAGE_REPO_NAME: docker.cloudsmith.io/diligent/sre-dev-paved-road/codebuild-frontend-example
      ignore-failure: false
    - identifier: backend
      buildspec: ./aws-code-resources/buildspec.yaml
      env:
        variables:
          BUILD_ID: backend
          APPDIR: ./backend
          TAGPREFIX: backend/
          IMAGE_REPO_NAME: docker.cloudsmith.io/diligent/sre-dev-paved-road/codebuild-frontend-example
      ignore-failure: false
